import { type Metadata } from 'next'

export const metadata: Metadata = { title: 'Terms of Service — FieldSightAI' }

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-20">
      <h1 className="text-3xl font-bold text-[#111827] mb-2">Terms of Service</h1>
      <p className="text-sm text-[#6B7280] mb-10">Last updated: April 2026</p>

      <div className="flex flex-col gap-8 text-[#374151] text-sm leading-relaxed">

        <section>
          <h2 className="text-base font-semibold text-[#111827] mb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using FieldSightAI (&ldquo;the platform&rdquo;), you agree to be bound by these Terms of Service. If you are using the platform on behalf of an organisation, you represent that you have authority to bind that organisation to these terms.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#111827] mb-2">2. Description of Service</h2>
          <p>FieldSightAI is a construction site documentation platform that ingests body camera footage, generates transcripts, and produces AI-assisted daily site reports. The platform integrates with RealPTT body cameras and may export data to third-party construction management platforms at your direction.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#111827] mb-2">3. User Accounts</h2>
          <ul className="list-disc pl-5 flex flex-col gap-1.5">
            <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
            <li>You must notify us immediately of any unauthorised use of your account.</li>
            <li>Accounts may not be shared between individuals.</li>
            <li>We reserve the right to suspend or terminate accounts that violate these terms.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#111827] mb-2">4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 flex flex-col gap-1.5 mt-2">
            <li>Use the platform for any unlawful purpose or in violation of any applicable laws.</li>
            <li>Record individuals without their knowledge in jurisdictions where consent is required.</li>
            <li>Attempt to access systems or data beyond your authorised role.</li>
            <li>Reverse engineer, decompile, or attempt to extract the source code of the platform.</li>
            <li>Use the platform to store or transmit malicious code.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text[#111827] mb-2">5. Recording Consent</h2>
          <p>You are solely responsible for ensuring that all persons who may be recorded using the platform have provided any consent required by applicable law. FieldSightAI does not verify consent and accepts no liability for recordings made without required consent.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#111827] mb-2">6. AI-Generated Content</h2>
          <p>Daily reports, task lists, and metadata tags generated by the platform are produced by AI and may contain errors or omissions. You are responsible for reviewing AI-generated content before relying on it for any purpose. FieldSightAI makes no warranty as to the accuracy or completeness of AI-generated content.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#111827] mb-2">7. Intellectual Property</h2>
          <p>You retain ownership of all recordings, transcripts, and site data you upload or create through the platform. You grant FieldSightAI a limited licence to process and store this data solely to provide the service. FieldSightAI retains all rights to the platform software, design, and AI models.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#111827] mb-2">8. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, FieldSightAI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the platform. Our total liability for any claim shall not exceed the fees paid by you in the twelve months preceding the claim.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#111827] mb-2">9. Service Availability</h2>
          <p>We aim to maintain high availability but do not guarantee uninterrupted access to the platform. We may perform maintenance, updates, or modifications at any time. We will endeavour to provide reasonable notice of planned downtime.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#111827] mb-2">10. Termination</h2>
          <p>Either party may terminate the agreement at any time. Upon termination, your access to the platform will cease. We will retain your data for 30 days following termination, after which it may be permanently deleted. You may request an export of your data before termination.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#111827] mb-2">11. Governing Law</h2>
          <p>These terms are governed by the laws of New South Wales, Australia. Any disputes shall be subject to the exclusive jurisdiction of the courts of New South Wales.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#111827] mb-2">12. Contact</h2>
          <p>Questions about these terms? Contact us at <a href="mailto:legal@fieldsightai.com" className="text-[#FF8F00] hover:underline">legal@fieldsightai.com</a>.</p>
        </section>

      </div>
    </div>
  )
}
