version = 0.1

[default.deploy.parameters]
stack_name = "fieldsightai-lambdas"
resolve_s3 = true
s3_prefix = "fieldsightai-lambdas"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VideosBucket=\"fsai-videos\" TranscriptsBucket=\"fsai-transcripts\" EventBusName=\"fieldsightai-events\""
image_repositories = []

[default.global.parameters]
region = "ap-southeast-2"
